(use-package elfeed
  :ensure t
  :config
  (setq elfeed-feeds
	'(("https://feeds.arstechnica.com/arstechnica/technology-lab" news security)
	  ("https://bleepingcomputer.com/feed/" news security)
	  ("https://googleonlinesecurity.blogspot.com/atom.xml" news google security)
	  ("https://bughunters.google.com/feed/en" google security)
	  ("https://www.grahamcluley.com/feed/" security)
	  ("https://jfrog.com/blog/feed" security)
	  ("https://krebsonsecurity.com/feed/" security)
	  ("https://www.schneier.com/feed/atom/" security crypto)
	  ("https://feeds.feedburner.com/TroyHunt" security)
	  ("https://feeds.feedburner.com/TheHackersNews" news)
	  ("https://lobste.rs/top/rss" tech)
	  ("https://lwn.net/headlines/rss" tech kernel)
	  ("https://www.kernel.org/feeds/kdist.xml" kernel)
	  ("https://risky.biz/feeds/risky-business/" security)
	  ("https://risky.biz/feeds/risky-business-news/" security)
	  ("https://www.theregister.com/security/research/headlines.atom" news)
	  ("https://www.theregister.com/security/patches/headlines.atom" news)
	  ("https://www.theregister.com/security/cyber_crime/headlines.atom" news)
	  ("https://www.darkreading.com/rss.xml" news)
	  ("https://soatok.blog/feed/" crypto)
	  ("https://portswigger.net/research/rss" vuln)
	  ("https://ngailong.wordpress.com/feed/" vuln)
	  ("https://edoverflow.com/index.xml" vuln)
	  ("https://a13xp0p0v.github.io/feed" vuln)
	  ("https://blog.exodusintel.com/feed/" vuln)
	  ("https://blog.isosceles.com/rss/" vuln)
	  ("https://connormcgarr.github.io/feed.xml" vuln)
	  ("https://blog.pi3.com.pl/?feed=rss2" vuln)
	  ("https://www.matteomalvica.com/index.xml" vuln)
	  ("https://blog.badsectorlabs.com/feeds/all.atom.xml" vuln)
	  ("https://fareedfauzi.github.io/feed" vuln))))
