(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (add-to-list 'meow-mode-state-list
               '(magit-mode . motion))
  (add-to-list 'meow-mode-state-list
               '(magit-status-mode . motion))
  (meow-motion-overwrite-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("/" . consult-line)
   )
  (setq meow-selection-command-fallback
        '((meow-change . meow-change-char)
          (meow-kill . meow-c-k)
          ;;(meow-kill . meow-delete)
          ;; (meow-cancel-selection . keyboard-quit)
          (meow-cancel-selection . ignore)
          (meow-pop-selection . meow-pop-grab)
          (meow-beacon-change . meow-beacon-change-char)))
  (meow-leader-define-key
   ;; spc j/k will run the original command in motion state.
   '("j" . "h-j")
   '("k" . "h-k")
   '("/" . "h-/")
   '("f" . consult-ripgrep)
   ;; use spc (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '(")" . meow-forward-slurp)
   '("(" . meow-forward-barf)
   '("{" . meow-backward-slurp)
   '("}" . meow-backward-barf)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("b" . meow-back-word)
   '("B" . backward-word)
   ;; '("B" . meow-back-symbol)
   '("c" . meow-change)
   ;; '("d" . meow-delete)
   '("d" . meow-kill)
   ;; '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . forward-word)
   ;; '("E" . meow-next-symbol)
   '("f" . meow-find)
   ;; '("F" . isearch-forward)
   '("g" . meow-join)
   ;; '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '(":a" . meow-left)
   '(":b" . meow-right)
   ;; '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . avy-goto-char-timer)
   '("n" . meow-search)
   '("o" . meow-open-below)
   '("O" . meow-open-above)
   ;; '("o" . meow-block)
   ;; '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-grab)
   ;; '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . undo-redo)
   ;;'("U" . meow-undo-in-selection)
   ;; '("v" . meow-visit)
   '("v" . meow-block)
   '("V" . meow-to-block)
   '("/" . consult-line)
   '("?" . comment-dwim)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-line-expand)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . meow-cancel-selection)
   '("%" . meow-query-replace)
   '("&" . meow-query-replace-regexp)
   ))

(use-package meow
  :ensure t
  :config
  (meow-setup)
  (meow-global-mode 1))
