 ;;; config-elfeed.el --- My RSS reader config -*- lexical-binding: t; -*-

(use-package elfeed
  :config
  (setq elfeed-feeds
        '(("https://feeds.arstechnica.com/arstechnica/technology-lab" news)
          ("https://bleepingcomputer.com/feed/" news)
          ("https://googleonlinesecurity.blogspot.com/atom.xml" news)
          ("https://bughunters.google.com/feed/en" websec)
          ("https://www.grahamcluley.com/feed/" news malware)
          ("https://krebsonsecurity.com/feed/" news)
          ("https://feeds.feedburner.com/TroyHunt" websec)
          ("https://feedfry.com/rss/11f0f1f20f2f93aa96c7f28157abe8ad" ai)
          ("https://feeds.feedburner.com/TheHackersNews" news)
          ("https://risky.biz/feeds/risky-business/" news)
          ("https://risky.biz/feeds/risky-business-news/" news)
          ("https://www.theregister.com/security/research/headlines.atom" news research)
          ("https://www.theregister.com/security/patches/headlines.atom" news)
          ("https://www.theregister.com/security/cyber_crime/headlines.atom" news)
          ("https://www.darkreading.com/rss.xml" news)
          ("https://soatok.blog/feed/" crypto research)
          ("https://www.schneier.com/feed/atom/" crypto research)
          ("https://portswigger.net/research/rss" websec research)
          ("https://ngailong.wordpress.com/feed/" websec research)
          ("https://edoverflow.com/index.xml" websec research)
          ("https://a13xp0p0v.github.io/feed" websec research)
          ("https://blog.exodusintel.com/feed/" redteam research)
          ("https://blog.isosceles.com/rss/" redteam research)
          ("https://connormcgarr.github.io/feed.xml" redteam research)
          ("https://blog.pi3.com.pl/?feed=rss2" redteam research)
	  ("http://www.icewall.pl/?feed=rss2" redteam research)
	  ("https://tyranidslair.blogspot.com/feeds/posts/default" redteam research)
          ("https://www.matteomalvica.com/index.xml" redteam research)
          ("https://blog.badsectorlabs.com/feeds/all.atom.xml" malware research)
          ("https://fareedfauzi.github.io/feed" malware research)
          ("https://blog.malwaremustdie.org/feeds/posts/default" malware research)
          ("https://www.blackhillsinfosec.com/feed/" redteam research)
          ("https://andresriancho.com/blog/feed/" redteam research)
          ("https://seclists.org/rss/oss-sec.rss" research)
          ("https://seclists.org/rss/fulldisclosure.rss" research)
          ("https://cirosec.de/en/blog/feed/" redteam research news)
          ("https://trustedsec.com/feed.rss" redteam research news)
          ("https://www.rapid7.com/rss.xml" redteam research news)
          ("https://www.crowdstrike.com/en-us/blog/feed" redteam research news)
          ("https://www.outflank.nl/blog/feed" redteam)
          ("https://www.vusec.net/feed/" redteam research)
	  ("https://jmpesp.me/rss/" binsec research)
	  ("https://blog.trailofbits.com/feed/" research)
	  ("http://tsyrklevich.net/feed.xml" research reverse)
	  ("http://blog.rewolf.pl/blog/?feed=rss2" research reverse)
	  ("http://x9090.blogspot.com/feeds/posts/default" research reverse binsec)
	  ("http://addxorrol.blogspot.com/feeds/posts/default" binsec research)
	  ("https://adamdoupe.com/atom.xml" research websec binsec))))

(provide 'config-elfeed)
