 ;;; config-elfeed.el --- My RSS reader config -*- lexical-binding: t; -*-

(use-package elfeed
  :config
  (setq elfeed-feeds
	'(("https://feeds.arstechnica.com/arstechnica/technology-lab" news security)
	  ("https://bleepingcomputer.com/feed/" news security)
	  ("https://googleonlinesecurity.blogspot.com/atom.xml" news google security)
	  ("https://bughunters.google.com/feed/en" google security)
	  ("https://www.grahamcluley.com/feed/" security)
	  ("https://jfrog.com/blog/feed" security)
	  ("https://krebsonsecurity.com/feed/" security)
	  ("https://www.schneier.com/feed/atom/" security crypto)
	  ("https://feeds.feedburner.com/TroyHunt" security)
	  ("https://feedfry.com/rss/11f0f1f20f2f93aa96c7f28157abe8ad" ai security)
	  ("https://feeds.feedburner.com/TheHackersNews" news)
	  ("https://lobste.rs/top/rss" tech)
	  ("https://lwn.net/headlines/rss" tech kernel)
	  ("https://www.kernel.org/feeds/kdist.xml" kernel)
	  ("https://risky.biz/feeds/risky-business/" security)
	  ("https://risky.biz/feeds/risky-business-news/" security)
	  ("https://www.theregister.com/security/research/headlines.atom" news)
	  ("https://www.theregister.com/security/patches/headlines.atom" news)
	  ("https://www.theregister.com/security/cyber_crime/headlines.atom" news)
	  ("https://www.darkreading.com/rss.xml" news)
	  ("https://soatok.blog/feed/" crypto)
	  ("https://portswigger.net/research/rss" research)
	  ("https://ngailong.wordpress.com/feed/" research)
	  ("https://edoverflow.com/index.xml" research)
	  ("https://a13xp0p0v.github.io/feed" research)
	  ("https://blog.exodusintel.com/feed/" research)
	  ("https://blog.isosceles.com/rss/" research)
	  ("https://connormcgarr.github.io/feed.xml" research)
	  ("https://blog.pi3.com.pl/?feed=rss2" research)
	  ("https://www.matteomalvica.com/index.xml" research)
	  ("https://blog.badsectorlabs.com/feeds/all.atom.xml" research)
	  ("https://fareedfauzi.github.io/feed" research)
	  ("https://www.blackhillsinfosec.com/feed/" research)
	  ("https://seclists.org/rss/oss-sec.rss" mail)
	  ("https://seclists.org/rss/fulldisclosure.rss" mail)
	  ("https://www.rapid7.com/rss.xml" research news)
	  ("https://www.outflank.nl/blog/feed" research))))

(provide 'config-elfeed)
